# see docs at https://docs.haskellstack.org/en/stable/yaml_configuration/
name:                AetherlingSTIR
version:             0.1.0.0
github:              "David-Durst/Aetherling/theory/AetherlingSTIR"
license:             BSD3
author:              "David Durst"
maintainer:          "davidbdurst@gmail.com"
copyright:           "2018 David Durst"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/David-Durst/Aetherling/theory/AetherlingSTIR#readme>

dependencies:
- base >= 4.7 && < 5
- pretty-simple >= 2.1.0.0 && < 2.2.0.0
- array >= 0.5.2.0 && < 0.6.0.0

ghc-options:
- -fwarn-incomplete-patterns 
    #- -Wall - comeback to this, too many warnings right now to handle

library:
  source-dirs: src/Core/

executables:
  AetherlingSTIR-Example-exe:
    main:                Main.hs
    source-dirs:
    - src/Examples/
    - src/ExamplesExe/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AetherlingSTIR

tests:
  AetherlingSTIR-Examples-test:
    main:                TestExamples.hs
    source-dirs:
    - test/ 
    - src/Examples/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AetherlingSTIR
    - tasty >= 1.0.0.0 && < 2.0.0.0
    - tasty-hunit >= 0.10.0.0
